# filebeat.yml

filebeat.prospectors:
- type: log
#  json.message_key: log
#  json.keys_under_root: true
#  enabled: true
#  encoding: utf-8
#  document_type: docker
  paths:
    - '/usr/share/filebeat/dockerlogs/*/*.log'
processors:
# decode the log field (sub JSON document) if JSONencoded, then maps it's fields to elasticsearch fields
#    fields: ["log"]
#    target: ""
#    overwrite_keys: true
- add_docker_metadata: "unix:///var/run/docker.sock"
 
filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

setup.template.settings:
  index.number_of_shards: 3
  
setup.kibana:
  host: "bjo-01.dev.citra.digital:5601"
  protocol: "http"
# identification required for X-pack  
#  username: "my_login"
#  password: "my_password"

output.elasticsearch:
  hosts: ["bjo-01.dev.citra.digital:9200"]
  protocol: "http"
# identification required for X-pack  
#  username: "my_login"
#  password: "my_password"

# Write Filebeat own logs only to file to avoid catching them with itself in docker log files
logging.to_files: true
logging.to_syslog: false

# X-pack optional module
#xpack.monitoring.enabled: true
#xpack.monitoring.elasticsearch:

