version: "3.5"
services:
  filebeat:
    hostname: filebeat
    image: herpiko/filebeat:latest
    volumes:
# needed to persist filebeat tracking data :
     - "filebeat_data:/usr/share/filebeat/data:rw"
# needed to access all docker logs (read only) :
     - "/var/lib/docker/containers:/usr/share/filebeat/dockerlogs:ro"
# needed to access additional informations about containers
     - "/var/run/docker.sock:/var/run/docker.sock"
  elk:
    hostname: elk
    image: sebp/elk
    ports:
     - "5601:5601"
     - "9200:9200"
     - "5044:5044"
#    environment:
#     - ELASTIC_BOOTSTRAP_PASSWORD="changeme"
#     - ELASTICSEARCH_USER=elastic
#     - ELASTICSEARCH_PASSWORD=omama123
#     - LOGSTASH_USER=elastic
#     - LOGSTASH_PASSWORD=omama123
#     - KIBANA_USER=kibana
#     - KIBANA_PASSWORD=omama123

volumes:
# create a persistent volume for Filebeat
  filebeat_data:
